name: Cypress Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cypress:
    runs-on: ubuntu-latest

    services:
      api:
        image: node:18
        ports:
          - 4000:4000
        working-directory: /app/apps/api
        volumes:
          - ./apps/api:/app
        options: >  
          --health-cmd="npm test" --health-interval=10s --health-timeout=5s --health-retries=5
        command: >
          sh -c "npm install && npm run dev"

      web:
        image: node:18
        ports:
          - 3000:3000
        working-directory: /app/apps/web
        volumes:
          - ./apps/web:/app
        options: >  
          --health-cmd="npm test" --health-interval=10s --health-timeout=5s --health-retries=5
        command: >
          sh -c "npm install && npm run dev"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies for Cypress
        run: |
          cd ./apps/api
          npm install
          cd ../web
          npm install
          cd ../../
          npm install

      - name: Run Cypress tests
        run: npx cypress run --headed --
