name: Cypress Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies for API
        run: |
          cd apps/api
          npm install

      - name: Install dependencies for Web
        run: |
          cd apps/web
          npm install

      - name: Start API
        run: |
          cd apps/api
          nohup npm run dev &  

      - name: Start Web
        run: |
          cd apps/web
          nohup npm run dev &  

      - name: Wait for the Web to be ready
        run: |
          for i in {1..20}; do
            if curl -s http://localhost:3000 > /dev/null; then
              echo "Web is up!"
              break
            else
              echo "Waiting for the Web to be up... Attempt $i"
              sleep 10
            fi
          done

      - name: Run Cypress tests
        env:
          NODE_OPTIONS: '--loader ts-node/esm'
        run: npx cypress run
