name: Cypress Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cypress:
    runs-on: ubuntu-latest

    services:
      api:
        image: node:18
        ports:
          - 4000:4000  # Port where the API will be exposed
        env:
          NODE_ENV: development
        options: >  # Health check options
          --health-cmd="npm test" --health-interval=10s --health-timeout=5s --health-retries=5

      web:
        image: node:18
        ports:
          - 3000:3000  # Port where the web app will be exposed
        env:
          NODE_ENV: development
        options: >  # Health check options
          --health-cmd="npm test" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies for API
        run: |
          cd apps/api
          npm install

      - name: Install dependencies for Web
        run: |
          cd ../web
          npm install

      - name: Install Cypress dependencies
        run: npm install

      - name: Run Cypress tests
        run: npx cypress run --headed --no-sandbox
