name: Cypress Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List directory structure
        run: ls -R

      - name: Remove old containers
        run: |
          docker ps -aq --filter "name=api" | xargs --no-run-if-empty docker rm -f
          docker ps -aq --filter "name=web" | xargs --no-run-if-empty docker rm -f

      - name: Install dependencies for API
        run: |
          cd apps/api
          npm install

      - name: Install dependencies for Web
        run: |
          cd apps/web
          npm install

      - name: Install Cypress dependencies
        run: npm install

      - name: Run API and Web services
        run: |
          docker run -d --name api -p 4000:4000 -e NODE_ENV=development node:18
          docker run -d --name web -p 3000:3000 -e NODE_ENV=development node:18

      - name: Run Cypress tests
        run: npx cypress run
